oc_core_homepage:
    path:     /hello/{name}
    defaults: { _controller: OCCoreBundle:Default:index }

oc_core_index:
    path:      /
    defaults:  { _controller: OCCoreBundle:Core:index}

oc_core_contact:
    path:      /contact
    defaults:  { _controller: OCCoreBundle:Core:contact}
