# src/OC/PlatformBundle/Resources/config/services.yml

services:
    oc_platform.advert_purger:
        class: OC\PlatformBundle\AdvertPurger\OCAdvertPurger
        arguments: [ @doctrine.orm.entity_manager ]
