# src/OC/PlatformBundle/Resources/config/services.yml

services:
    oc_platform.advert_purger:
        class: OC\PlatformBundle\AdvertPurger\OCAdvertPurger
        arguments: [ @doctrine.orm.entity_manager ]

    oc_platform.antispam:
        class:     OC\PlatformBundle\Antispam\OCAntispam
        arguments: [@mailer, 50]
        tags:
            -  { name: twig.extension }
        calls:
            - [ setLocale, [ %locale% ] ]

    oc_platform.beta.html:
        class: OC\PlatformBundle\Beta\BetaHTML